{% set name = "fickling" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fickling-{{ version }}.tar.gz
  sha256: cb06bbb7b6a1c443eacf230ab7e212d8b4f3bb2333f307a8c94a144537018888

build:
  entry_points:
    - fickling = fickling.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - astunparse >=1.6.3,<1.7.dev0

test:
  imports:
    - fickling
  commands:
    - pip check
    - fickling --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trailofbits/fickling
  summary: A static analyzer and interpreter for Python pickle data
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
