schema_version: 1

context:
  name: fickling
  version: "0.1.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fickling-${{ version }}.tar.gz
  sha256: 25a0bc7acda76176a9087b405b05f7f5021f76079aa26c6fe3270855ec57d9bf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fickling = fickling.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - fickling
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - fickling --help

about:
  summary: A static analyzer and interpreter for Python pickle data
  license: LGPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/trailofbits/fickling

extra:
  recipe-maintainers:
    - thewchan
