schema_version: 1

context:
  name: fickling
  version: 0.1.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fickling-${{ version }}.tar.gz
  sha256: cb06bbb7b6a1c443eacf230ab7e212d8b4f3bb2333f307a8c94a144537018888

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fickling = fickling.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - stdlib-list ~=0.11.1
    # not listed in dependencies but needed to past import
    - typing_extensions

tests:
  - python:
      imports:
        - fickling
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}
    script:
      - fickling --help

about:
  summary: A static analyzer and interpreter for Python pickle data
  license: LGPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/trailofbits/fickling

extra:
  recipe-maintainers:
    - thewchan
